# 배포 환경 설정
spring:
  profiles:
    active:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://era-server-database.cqdhf53pi1e5.ap-northeast-2.rds.amazonaws.com:3306/era?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: founders2021!
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
